title: First Impressions
author: Mel Brockley
email: msbrockley@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Mel Brockley, web application developer, extraordinary (noun)

# social links
#twitter_username: your-twitter-handle
github_username:  MellifluousBee

show_excerpts: true # set to false to remove excerpts on the homepage

#theme: jekyll-theme-midnight
theme: minima
